export const UPLOAD_FILE = 'BASIC/UPLOAD_FILE';

export const FETCH_FILE_DATA = 'BASIC/FETCH_FILE_DATA';
export const FETCH_FILE_DATA_SUCCESS = 'BASIC/FETCH_FILE_DATA_SUCCESS';
export const FETCH_FILE_DATA_FAILED = 'BASIC/FETCH_FILE_DATA_FAILED';

export const FETCH_USERS = 'BASIC/FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'BASIC/FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'BASIC/FETCH_USERS_FAILED';

