export const SAVE_USER_INFO = 'AUTH/SAVE_USER_INFO';
export const SAVE_USER_INFO_SUCCESS = 'AUTH/SAVE_USER_INFO_SUCCESS';
export const SAVE_USER_INFO_FAILED = 'AUTH/SAVE_USER_INFO_FAILED';

export const USER_LOGIN = 'AUTH/USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'AUTH/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'AUTH/USER_LOGIN_FAILED';

export const CHECK_REFRESH = 'AUTH/CHECK_REFRESH';
export const CHECK_REFRESH_SUCCESS = 'AUTH/CHECK_REFRESH_SUCCESS';
export const CHECK_REFRESH_FAILED = 'AUTH/CHECK_REFRESH_FAILED';

export const SET_MSG = 'AUTH/SET_MSG';

